[package]
name = "miller_rabin_naughty_witness"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "miller_rabin"
harness = false
